<template>
  <vue-good-table
    :columns="columns"
    :rows="rows"
    :line-numbers="false"
    max-height="200px"
    :search-options="{
      enabled: true,
    }"
    :pagination-options="{
      enabled: true,
      mode: 'records',
    }"
    :compactMode="true"
  >
    <template #table-actions> </template>
  </vue-good-table>
</template>

<script>
export default {
  name: "my-component",
  data() {
    return {
      columns: [
        {
          label: "Name",
          field: "name",
        },
        {
          label: "Age",
          field: "age",
        },
        {
          label: "Position",
          field: "position",
        },
        {
          label: "Office",
          field: "office",
        },
        {
          label: "Salary",
          field: "salary",
        },
      ],
      rows: [
        {
          id: 1,
          name: "Tiger Nixon",
          position: "System Architect",
          office: "Edinburgh",
          age: 61,
          salary: 320800,
        },
        {
          id: 2,
          name: "Garrett Winters",
          position: "Accountant",
          office: "Tokyo",
          age: 63,
          salary: 170750,
        },
        {
          id: 3,
          name: "Ashton Cox",
          position: "Junior Technical Author",
          office: "San Francisco",
          age: 66,
          salary: 86000,
        },
        {
          id: 4,
          name: "Cedric Kelly",
          position: "Senior Javascript Developer",
          office: "Edinburgh",
          age: 22,
          salary: 433060,
        },
        {
          id: 5,
          name: "Airi Satou",
          position: "Accountant",
          office: "Tokyo",
          age: 33,
          salary: 162700,
        },
        {
          id: 6,
          name: "Brielle Williamson",
          position: "Integration Specialist",
          office: "New York",
          age: 61,
          salary: 372000,
        },
        {
          id: 7,
          name: "Herrod Chandler",
          position: "Sales Assistant",
          office: "San Francisco",
          age: 59,
          salary: 137500,
        },
        {
          id: 8,
          name: "Rhona Davidson",
          position: "Integration Specialist",
          office: "Tokyo",
          age: 55,
          salary: 327900,
        },
        {
          id: 9,
          name: "Colleen Hurst",
          position: "Javascript Developer",
          office: "San Francisco",
          age: 39,
          salary: 205500,
        },
        {
          id: 10,
          name: "Sonya Frost",
          position: "Software Engineer",
          office: "Edinburgh",
          age: 23,
          salary: 103600,
        },
        {
          id: 11,
          name: "Jena Gaines",
          position: "Office Manager",
          office: "London",
          age: 30,
          salary: 90560,
        },
        {
          id: 12,
          name: "Quinn Flynn",
          position: "Support Lead",
          office: "Edinburgh",
          age: 22,
          salary: 342000,
        },
        {
          id: 13,
          name: "Paul Byrd",
          position: "Chief Financial Officer (CFO)",
          office: "New York",
          age: 64,
          salary: 725000,
        },
        {
          id: 14,
          name: "Gloria Little",
          position: "Systems Administrator",
          office: "New York",
          age: 59,
          salary: 237500,
        },
        {
          id: 15,
          name: "Bradley Greer",
          position: "Software Engineer",
          office: "London",
          age: 41,
          salary: 132000,
        },
        {
          id: 16,
          name: "Dai Rios",
          position: "Personnel Lead",
          office: "Edinburgh",
          age: 35,
          salary: 217500,
        },
        {
          id: 17,
          name: "Jenette Caldwell",
          position: "Development Lead",
          office: "New York",
          age: 30,
          salary: 345000,
        },
        {
          id: 18,
          name: "Yuri Berry",
          position: "Chief Marketing Officer (CMO)",
          office: "New York",
          age: 40,
          salary: 675000,
        },
        {
          id: 19,
          name: "Caesar Vance",
          position: "Pre-Sales Support",
          office: "New York",
          age: 21,
          salary: 106450,
        },
        {
          id: 20,
          name: "Doris Wilder",
          position: "Sales Assistant",
          office: "Sidney",
          age: 23,
          salary: 85600,
        },
        {
          id: 21,
          name: "Angelica Ramos",
          position: "Chief Executive Officer (CEO)",
          office: "London",
          age: 47,
          salary: 1200000,
        },
        {
          id: 22,
          name: "Gavin Joyce",
          position: "Developer",
          office: "Edinburgh",
          age: 42,
          salary: 92575,
        },
        {
          id: 23,
          name: "Jennifer Chang",
          position: "Regional Director",
          office: "Singapore",
          age: 28,
          salary: 357650,
        },
        {
          id: 24,
          name: "Brenden Wagner",
          position: "Software Engineer",
          office: "San Francisco",
          age: 28,
          salary: 206850,
        },
        {
          id: 25,
          name: "Fiona Green",
          position: "Chief Operating Officer (COO)",
          office: "San Francisco",
          age: 48,
          salary: 850000,
        },
        {
          id: 26,
          name: "Shou Itou",
          position: "Regional Marketing",
          office: "Tokyo",
          age: 20,
          salary: 163000,
        },
        {
          id: 27,
          name: "Michelle House",
          position: "Integration Specialist",
          office: "Sidney",
          age: 37,
          salary: 95400,
        },
        {
          id: 28,
          name: "Suki Burks",
          position: "Developer",
          office: "London",
          age: 53,
          salary: 114500,
        },
        {
          id: 29,
          name: "Prescott Bartlett",
          position: "Technical Author",
          office: "London",
          age: 27,
          salary: 145000,
        },
        {
          id: 30,
          name: "Gavin Cortez",
          position: "Team Leader",
          office: "San Francisco",
          age: 22,
          salary: 235500,
        },
        {
          id: 31,
          name: "Martena Mccray",
          position: "Post-Sales support",
          office: "Edinburgh",
          age: 46,
          salary: 324050,
        },
        {
          id: 32,
          name: "Unity Butler",
          position: "Marketing Designer",
          office: "San Francisco",
          age: 47,
          salary: 85675,
        },
        {
          id: 33,
          name: "Howard Hatfield",
          position: "Office Manager",
          office: "San Francisco",
          age: 51,
          salary: 164500,
        },
        {
          id: 34,
          name: "Hope Fuentes",
          position: "Secretary",
          office: "San Francisco",
          age: 41,
          salary: 109850,
        },
        {
          id: 35,
          name: "Vivian Harrell",
          position: "Financial Controller",
          office: "San Francisco",
          age: 62,
          salary: 452500,
        },
        {
          id: 36,
          name: "Timothy Mooney",
          position: "Office Manager",
          office: "London",
          age: 37,
          salary: 136200,
        },
        {
          id: 37,
          name: "Jackson Bradshaw",
          position: "Director",
          office: "New York",
          age: 65,
          salary: 645750,
        },
        {
          id: 38,
          name: "Olivia Liang",
          position: "Support Engineer",
          office: "Singapore",
          age: 64,
          salary: 234500,
        },
        {
          id: 39,
          name: "Bruno Nash",
          position: "Software Engineer",
          office: "London",
          age: 38,
          salary: 163500,
        },
        {
          id: 40,
          name: "Sakura Yamamoto",
          position: "Support Engineer",
          office: "Tokyo",
          age: 37,
          salary: 139575,
        },
        {
          id: 41,
          name: "Thor Walton",
          position: "Developer",
          office: "New York",
          age: 61,
          salary: 98540,
        },
        {
          id: 42,
          name: "Finn Camacho",
          position: "Support Engineer",
          office: "San Francisco",
          age: 47,
          salary: 87500,
        },
        {
          id: 43,
          name: "Serge Baldwin",
          position: "Data Coordinator",
          office: "Singapore",
          age: 64,
          salary: 138575,
        },
        {
          id: 44,
          name: "Zenaida Frank",
          position: "Software Engineer",
          office: "New York",
          age: 63,
          salary: 125250,
        },
        {
          id: 45,
          name: "Zorita Serrano",
          position: "Software Engineer",
          office: "San Francisco",
          age: 56,
          salary: 115000,
        },
        {
          id: 46,
          name: "Jennifer Acosta",
          position: "Junior Javascript Developer",
          office: "Edinburgh",
          age: 43,
          salary: 75650,
        },
        {
          id: 47,
          name: "Cara Stevens",
          position: "Sales Assistant",
          office: "New York",
          age: 46,
          salary: 145600,
        },
        {
          id: 48,
          name: "Hermione Butler",
          position: "Regional Director",
          office: "London",
          age: 47,
          salary: 356250,
        },
        {
          id: 49,
          name: "Lael Greer",
          position: "Systems Administrator",
          office: "London",
          age: 21,
          salary: 103500,
        },
        {
          id: 50,
          name: "Jonas Alexander",
          position: "Developer",
          office: "San Francisco",
          age: 30,
          salary: 86500,
        },
        {
          id: 51,
          name: "Shad Decker",
          position: "Regional Director",
          office: "Edinburgh",
          age: 51,
          salary: 183000,
        },
        {
          id: 52,
          name: "Michael Bruce",
          position: "Javascript Developer",
          office: "Singapore",
          age: 29,
          salary: 183000,
        },
        {
          id: 53,
          name: "Donna Snider",
          position: "Customer Support",
          office: "New York",
          age: 27,
          salary: 112000,
        },
      ],
    };
  },
};
</script>
